### PR TITLE
version 0 of designops.github.io

### PR DESCRIPTION
**Pull request by filtercake**
I want to get up an entry point quickly.

The goal is to get people into the disussion who have vague understanding for the term and/or are familiar with the mentioned resources.

I'm aware that the code is not really accessible, undocumented, hacky, etc, but I do not want all of this to block pulling people in :)

My questions are

- Do you have a concern that should block this version from release?
- Do you have feedback on improving content and design? (will probably break that into tickets like #4)

image

image

### CODE REVIEW

**Comment by filtercake** [comment]
updated and moved some tasks to https://github.com/DesignOps/designops.github.io/issues/4

:shipit:

**Comment by KlausTrainer** [comment]
This website is a great entry point, and I like its simplicity! :+1:

I like the fact that it provides just three resources for introducing people to the topic, plus the invitation to contribute in addition. I believe that there's a sweet spot between providing enough to enable people to getting started, and not too much, which could make some newcomers already feel overburdened right at the beginning. (As soon as newcomers have caught interest and are proceeding on their own, they'll likely find more anyway.) To me, it feels like that sweet spot is around three to at most five things at a time.

Although I'd expect to find more content (getting started, contributing, etc.) right in the README – even early on – I don't think that this needs to block a release :)

**Comment by kaelig** [comment]
Thank you for doing this, it's a great start.

We can refine the image and branding as the movement evolves.

I think it'd make sense to add a list of people to follow/read somewhere, a bit like this. https://uptodate.frontendrescue.org/ Not sure it should be part of this first iteration. Your call.

**Comment by filtercake** [comment]
thx all so far!

found a copy bug in the footer:

> Please share your thoughts on this site and on DesignOps on general.

Want to change to 

> Please share your thoughts **about** this site and on DesignOps **in** general.

@kaelig 

> list of people to follow... (Not sure it needs to be part of this first iteration. Your call.)

i like the idea, have some thoughts on it though. I openend #5

**Comment by filtercake** [comment]
added a note to the upcoming coc to the footer.

**Pull request merged**
